/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import Employer.Employer;
import Loan.AddLoan;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asus
 */
public class Dashboard extends javax.swing.JFrame {

    private Employer currentUser;
    
    public Dashboard() {
        initComponents();
    }

    public Employer getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(Employer currentUser) {
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_view = new javax.swing.JMenu();
        m_view_creditCustomer = new javax.swing.JMenuItem();
        m_view_debitCustomer = new javax.swing.JMenuItem();
        m_view_collector = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        m_view.setText("View");
        m_view.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        m_view_creditCustomer.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        m_view_creditCustomer.setText("Credit Customer");
        m_view_creditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_view_creditCustomerActionPerformed(evt);
            }
        });
        m_view.add(m_view_creditCustomer);

        m_view_debitCustomer.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        m_view_debitCustomer.setText("Debit Customer");
        m_view.add(m_view_debitCustomer);

        m_view_collector.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        m_view_collector.setText("Collector");
        m_view.add(m_view_collector);

        jMenuBar1.add(m_view);

        jMenu8.setText("Customer");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu5.setText("Add Customer");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem10.setText("Credit Customer");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem13.setText("Debit Customer");
        jMenu5.add(jMenuItem13);

        jMenu8.add(jMenu5);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem14.setText("Update Customer");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem14);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Employee");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu7.setText("Add Employee");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem15.setText("Collector");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem16.setText("Manager");
        jMenu7.add(jMenuItem16);

        jMenu9.add(jMenu7);

        jMenu10.setText("Update Employee");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem33.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem33.setText("Collector");
        jMenu10.add(jMenuItem33);

        jMenuItem35.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem35.setText("Manager");
        jMenu10.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem36.setText("Executive Manager");
        jMenu10.add(jMenuItem36);

        jMenu9.add(jMenu10);

        jMenuBar1.add(jMenu9);

        jMenu4.setText("Loan");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem23.setText("Add Loan");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem24.setText("Update Loan");
        jMenu4.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem25.setText("Add Payment");
        jMenu4.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem26.setText("Update Payment");
        jMenu4.add(jMenuItem26);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Account");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem27.setText("Add Account");
        jMenu6.add(jMenuItem27);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem28.setText("Update Account");
        jMenu6.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem29.setText("Add Transaction");
        jMenu6.add(jMenuItem29);

        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem30.setText("Update Transaction");
        jMenu6.add(jMenuItem30);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Analyze");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem7.setText("Credit Customer");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem8.setText("Debit Customer");
        jMenu2.add(jMenuItem8);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem6.setText("Collector");
        jMenu2.add(jMenuItem6);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem17.setText("Loan");
        jMenu2.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem18.setText("Business");
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu11.setText("Holiday");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem31.setText("Manage Holidays");
        jMenu11.add(jMenuItem31);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        AddCreditCustomer frm = new AddCreditCustomer();
        frm.setVisible(true);        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void m_view_creditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_view_creditCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_view_creditCustomerActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        UpdateCreditCustomer frm = new UpdateCreditCustomer();
        frm.setVisible(true); 
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        AddLoan frm = new AddLoan();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu m_view;
    private javax.swing.JMenuItem m_view_collector;
    private javax.swing.JMenuItem m_view_creditCustomer;
    private javax.swing.JMenuItem m_view_debitCustomer;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
